service: ath-schedule-scraper-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  deploymentBucket:
    name: rtrydev-serverless-deployments-${opt:region}
  httpApi:
    cors:
      allowedOrigins: '*'
      allowedHeaders:
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token
        - X-Amz-User-Agent
      allowCredentials: false
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 'dynamodb:GetItem'
            - 'dynamodb:PutItem'
          Resource:
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/ath-schedule-branches
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/ath-schedule-blacklist
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
            - 's3:HeadObject'
          Resource:
            - arn:aws:s3:::ath-schedule-cache/*

package:
  individually: true
  patterns:
    - '!**/*'

functions:
  getBranch:
    package:
      patterns:
        - 'handlers/get_branch.py'
        - 'src/**/*'
    handler: handlers/get_branch.handler
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - httpApi:
          path: /branches/{branch_id}
          method: GET
  createBranch:
    package:
      patterns:
        - 'handlers/create_branch.py'
        - 'src/**/*'
    handler: handlers/create_branch.handler
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - httpApi:
          path: /branches
          method: POST
  getSchedule:
    package:
      patterns:
        - 'handlers/get_schedule.py'
        - 'src/**/*'
    handler: handlers/get_schedule.handler
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - httpApi:
          path: /schedules/{schedule_id}
          method: GET
  createSchedule:
    package:
      patterns:
        - 'handlers/create_schedule.py'
        - 'src/**/*'
    handler: handlers/create_schedule.handler
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - httpApi:
          path: /schedules
          method: POST

custom:
  pythonRequirements:
    layer: true

plugins:
  - serverless-deployment-bucket
  - serverless-python-requirements
